# Generated by Django 5.0.7 on 2024-07-23 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=100, verbose_name="Текст")),
                (
                    "text_color",
                    models.CharField(max_length=8, verbose_name="Цвет текста"),
                ),
                ("bg_color", models.CharField(max_length=8, verbose_name="Цвет фона")),
                ("font_size", models.IntegerField(default=40)),
                ("output_file", models.FilePathField(path="/out/")),
                (
                    "width",
                    models.IntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(1920)],
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(1080)],
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "fps",
                    models.IntegerField(
                        default=30,
                        validators=[django.core.validators.MaxValueValidator(60)],
                    ),
                ),
            ],
        ),
    ]
