# Generated by Django 5.0.7 on 2024-07-25 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_rename_output_file_user_requests_output_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_requests",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="bg_color",
            field=models.CharField(
                default="AAAAAA", max_length=8, verbose_name="Цвет фона"
            ),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="output_filename",
            field=models.TextField(default="output", verbose_name="Название файла"),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="text",
            field=models.TextField(
                default="Генератор текста бегущей строки",
                max_length=255,
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="text_color",
            field=models.CharField(
                default="333333", max_length=8, verbose_name="Цвет текста"
            ),
        ),
    ]
