# Generated by Django 5.0.7 on 2024-07-27 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0004_user_requests_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_requests",
            name="duration",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MaxValueValidator(30),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Длительность (сек.)",
            ),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="font_size",
            field=models.IntegerField(
                default=40, max_length=100, verbose_name="Размер шрифта"
            ),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="fps",
            field=models.IntegerField(
                default=30,
                validators=[
                    django.core.validators.MaxValueValidator(60),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Кадров в секунду",
            ),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="height",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MaxValueValidator(1080),
                    django.core.validators.MinValueValidator(25),
                ],
                verbose_name="Высота",
            ),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="output_filename",
            field=models.TextField(
                default="output",
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(255),
                ],
                verbose_name="Название файла",
            ),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="text",
            field=models.TextField(
                default="Генератор текста бегущей строки",
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(255),
                ],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="width",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MaxValueValidator(1920),
                    django.core.validators.MinValueValidator(25),
                ],
                verbose_name="Ширина",
            ),
        ),
    ]
