# Generated by Django 5.0.7 on 2024-07-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0005_alter_user_requests_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_requests",
            name="output_filename",
        ),
    ]
