# Generated by Django 5.0.7 on 2024-07-30 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0006_remove_user_requests_output_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_requests",
            name="height",
            field=models.IntegerField(
                default=250,
                validators=[
                    django.core.validators.MaxValueValidator(1080),
                    django.core.validators.MinValueValidator(25),
                ],
                verbose_name="Высота",
            ),
        ),
        migrations.AlterField(
            model_name="user_requests",
            name="width",
            field=models.IntegerField(
                default=250,
                validators=[
                    django.core.validators.MaxValueValidator(1920),
                    django.core.validators.MinValueValidator(25),
                ],
                verbose_name="Ширина",
            ),
        ),
    ]
