# Generated by Django 5.0.7 on 2024-07-30 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0007_alter_user_requests_height_alter_user_requests_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_requests",
            name="font_size",
            field=models.IntegerField(
                default=40,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Размер шрифта",
            ),
        ),
    ]
